image: docker:20.10.17

services:
  - docker:20.10.17-dind

variables:
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"

stages:
  - build
  - unit
  - test
  - covfuzz
  - deploy
  - dast
  - apifuzz

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/DAST.gitlab-ci.yml
  - template: API-Fuzzing.gitlab-ci.yml
  - template: Coverage-Fuzzing.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml

build:
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push "$IMAGE"

unit:
  image: python:latest
  stage: unit
  variables:
    NOTES_DB_BACKEND: "local"
  before_script:
    - apt update -y
    - apt install libmariadb3 libmariadb-dev sqlite3 libsqlite3-dev -y
    - pip3 install -r requirements.txt
  script:
    - python -m unittest tests/test_db.py 2>&1 | tee unit.txt
  artifacts:
    paths:
      - unit.txt

gemnasium-python-dependency_scanning:
  variables:
    SECURE_LOG_LEVEL: "debug"
  before_script:
    - apt update
    - apt install libmariadb3 libmariadb-dev sqlite3 libsqlite3-dev -y

container_scanning:
  variables:
    CS_DISABLE_LANGUAGE_VULNERABILITY_SCAN: "false"

coverage-guided-fuzzing:
  image: python:latest
  stage: covfuzz
  extends: .fuzz_base
  script:
    - pip install --extra-index-url https://gitlab.com/api/v4/projects/19904939/packages/pypi/simple pythonfuzz
    - ./gitlab-cov-fuzz run --engine pythonfuzz -- fuzz.py

deploy-staging:
  image: registry.gitlab.com/gitlab-org/cluster-integration/helm-install-image:helm-3.10.0-kube-1.24.6-alpine-3.15
  stage: deploy
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    HELM_HOST: "localhost:44134"
    NOTES_DB_BACKEND: "mariadb"
  before_script:
    - kubectl config use-context tech-marketing/devsecops/initech/simple-notes:simplenotes
    - helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
    - helm upgrade --install mariadb mariadb --repo https://charts.bitnami.com/bitnami --set auth.rootPassword=$DB_ROOT_PWD --set primary.service.clusterIP=None
  script:
    - kubectl config use-context tech-marketing/devsecops/initech/simple-notes:simplenotes
    - helm upgrade --install notes helm -f helm/values.yaml --set image=$IMAGE --set dbrootpwd=$DB_ROOT_PWD
  after_script:
    - kubectl config use-context tech-marketing/devsecops/initech/simple-notes:simplenotes
    - echo "DAST_WEBSITE=http://$(kubectl get svc -n ingress-nginx | grep LoadBalancer | awk '{print $4}')/notes" >> deploy.env
    - echo "INGRESS_LB_IP=$(kubectl get svc -n ingress-nginx | grep LoadBalancer | awk '{print $4}')" >> deploy.env
  environment:
    name: staging
  artifacts:
    reports:
      dotenv: deploy.env
  dependencies:
    - build

reset-notes-table:
  image: registry.gitlab.com/gitlab-org/cluster-integration/helm-install-image:helm-3.10.0-kube-1.24.6-alpine-3.15
  stage: deploy
  script:
    - kubectl config use-context tech-marketing/devsecops/initech/simple-notes:simplenotes
    - kubectl exec -it deploy/notes -- ./scripts/drop_table.py
  environment:
    name: staging
  allow_failure: true
  when: manual

dast:
  stage: dast
  variables:
     DAST_BROWSER_SCAN: "true"
     DAST_FULL_SCAN_ENABLED: "true"
  dependencies:
    - deploy-staging

apifuzzer_fuzz:
  stage: apifuzz
  before_script:
    - sed -i 's@HOST@'"${INGRESS_LB_IP}"'@' test_openapi.v2.0.json
    - export FUZZAPI_TARGET_URL=http://$(kubectl get svc -n ingress-nginx | grep LoadBalancer | awk '{print $4}')
  variables:
    FUZZAPI_PROFILE: Long-100
    FUZZAPI_OPENAPI: test_openapi.v2.0.json
  dependencies:
    - deploy-staging
