[secrets]
  description = 'secrets custom rules configuration'

  [[secrets.passthrough]]
    type  = "raw"
    target = "gitleaks.toml"
    value = """\
title = "gitleaks config"
[[rules]]
description = "Find Possible Hardcoded Values"
regex = "(password|pass|passwd|pwd|secret|token|admin|yeet)"
"""