[semgrep]
  description = "My custom ruleset for Semgrep"
  validate = true

  [[semgrep.passthrough]]
    type  = "raw"
    mode  = "append"
    value = """
- id: "secret"
  patterns:
    - pattern-either:
        - pattern: '$MASK'
    - metavariable-regex:
        metavariable: "$MASK"
        regex: "(password|pass|passwd|pwd|secret|token|admin|yeet)"
  message: |
    Possible use of a hard-coded password
  metadata:
    cwe: "..."
  severity: "ERROR"
  languages:
    - "python"
"""