[secrets]
  description = 'Hardcoded Credential Detection Extension'

  [[secrets.passthrough]]
    type  = "raw"
    target = "gitleaks.toml"
    value = """\
title = "gitleaks config"
# add regexes to the regex table
[[rules]]
description = "Possible Hardcoded Credentials"
regex = "(password|admin|yeet)"
"""