echo:
    port: 8080
    targetPort: 8080
    replicas: 1
restrictedecho:
    port: 8080
    targetPort: 8080
    replicas: 1
notes:
    port: 5000
    targetPort: 5000
    path: notes
    replicas: 1
    dbBackend: mariadb
