restrictednginx:
    name: restricted-nginx-production
    port: 80
    targetPort: 80
    replicas: 1
notes:
    name: notes-production
    port: 5000
    targetPort: 5000
    path: notes
    replicas: 1
    dbBackend: mariadb
    dbrootpwd: y33tboi
    dbName: production

    env:
      - name: DB_ROOT_PWD
        value: "y33tboi"
      - name: NOTES_DB_BACKEND
        value: "mariadb"
      - name: NOTES_DB_DATABASE
        value: "production"
      - name: NOTES_ING_PATH
        value: "notes"
      - name: CI_MERGE_REQUEST_PROJECT_ID
        value: ""
      - name: CI_MERGE_REQUEST_ID
        value: ""
      - name: 'CI_MERGE_REQUEST_SOURCE_BRANCH_SHA'
        value: ""
