restrictednginx:
  name: restricted-nginx-production
  port: 80
  targetPort: 80
  replicas: 1
  
notes:
  name: notes-production
  port: 5000
  targetPort: 5000
  path: notes
  replicas: 1
  dbBackend: mariadb
  dbrootpwd: y33tboi
  dbName: production

  env:
    CI_MERGE_REQUEST_PROJECT_ID: "37403244"
    CI_MERGE_REQUEST_ID: "15"
    CI_MERGE_REQUEST_SOURCE_BRANCH_SHA: "f8ed7a7e73a4694972335d29921b01efacc877c2"