echo:
    port: 8080
    targetPort: 8080
    replicas: 1
restrictednginx:
    port: 80
    targetPort: 80
    replicas: 1
notes:
    port: 5000
    targetPort: 5000
    path: notes
    replicas: 1
    dbBackend: mariadb
    dbrootpwd: y33tboi
